version: '3.1'

services:
    redmine:
        container_name: redmine
        image: redmine
        restart: unless-stopped
        ports:
            - 3000:3000
        volumes:
            - ./data/plugins:/usr/src/redmine/plugins
            - ./data/themes:/usr/src/redmine/public/themes
        environment:
            REDMINE_DB_MYSQL: redmine-db
            REDMINE_DB_PASSWORD: redmine
            SMTP_USER:
            SMTP_PASS:

    redmine-db:
        image: mariadb
        container_name: redmine-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: redmine
            MYSQL_DATABASE: redmine
        volumes:
            - ./data/db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci